name: pushed_updates
run-name: ${{ github.actor }} Update docs after changes are pushed.
on:    
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Turn this on to skip running the SSH script.
        default: false

jobs: 
  execute-command:
    name: Use tailscale to connect and execute command.
    runs-on: ubuntu-24.04
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: getting boolean status
        run: echo ${{inputs.dry-run}}
        shell: bash
      - name: executing remote ssh commands using password
        if: ${{ inputs.dry-run == false && github.ref_name == 'main'}}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_TS }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: /bin/sh /home/thatoneguy99/.docker/mkdocs/action_execute.sh
      - name: Dev- executing remote ssh commands using password
        if: ${{ inputs.dry-run == false && github.ref_name == 'develop'}}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_TS }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: /bin/sh /home/thatoneguy99/.docker/mkdocs/action_execute_dev.sh
      #- Saving the Discord notifications for later when there are less updates.    
      #- name: Actions for Discord
      #  if: ${{ github.ref_name == 'main'}}
      #  uses: Ilshidur/action-discord@0.3.2
      #  env:
      #    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      #  with:
      #    args: 'The docs have been updated. Take a look. https://docs.maintainerr.info'
