name: Mkdocs Deploy
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [maintainerr-release]
  workflow_dispatch:
    inputs:
      versionInput:
        description: 'Input version from Maintainerr release'
        required: true
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          ref: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.ref || github.ref}}
          sparse-checkout: |
            docs
            layouts
      - name: Extract Version Number
        id: extract_version
        run: |
        echo "version=$(grep -oP 'version: \K.*' docs/index.md)" >> $GITHUB_ENV
      - name: Log Extracted Version
        run: |
        echo "Extracted version: ${{ steps.extract_version.outputs.version }}"
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material- 
      - run: sudo apt-get install pngquant
      - run: pip install mkdocs-glightbox
      - run: pip install mkdocs-swagger-ui-tag
      - run: pip install "mkdocs-material[imaging]"
      - run: pip install mike
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-git-committers-plugin-2
      - run: pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: mike deploy --update-aliases ${{github.event.client_payload.versionInput || github.event.inputs.versionInput || env.version || '2.8.0'}} latest
      - run: mike set-default --push --allow-empty latest
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }} 
